export default {
	VALIDATION_ERROR: "VALIDATION_ERROR",
	USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
	FILE_UPLOADING_FAILD: "FILE_UPLOADING_FAILD",
	FILE_DELETING_FAILD: "FILE_DELETING_FAILD",
	USER_NOT_FOUND: "USER_NOT_FOUND",
	INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
	VALIDATION_ERROR: "VALIDATION_ERROR",
	INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
};
